version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: daily
      time: "15:00"
      timezone: "Europe/Oslo"
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: "Europe/Oslo"