---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-cert-notifier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-cert-notifier
  namespace: linkerd
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["linkerd-config"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-cert-notifier
  namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-cert-notifier
subjects:
- kind: ServiceAccount
  name: linkerd-cert-notifier
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: linkerd-cert-notifier
  name: linkerd-cert-notifier
  namespace: linkerd
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: linkerd-cert-notifier
  template:
    metadata:
      labels:
        job-name: linkerd-cert-notifier
    spec:
      containers:
        - image: ko://github.com/tjololo/linkerd-cert-notifier
          imagePullPolicy: IfNotPresent
          name: linkerd-cert-notifier
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      serviceAccountName: linkerd-cert-notifier
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: linkerd-cert-notifier
---
apiVersion: v1
data:
  config.yaml: |
    development: true
    slack:
      enabled: true
      # url: https://hooks.slack.com/services/......
      url: https://hooks.slack.com/services/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
      username: kind-cluster
      channel: linkerd-test
    earlyexpire:
      anchor: 14400h
      issuer: 14400h
kind: ConfigMap
metadata:
  name: linkerd-cert-notifier
  namespace: linkerd