apiVersion: v1
data:
  config.yaml: |
    development: {{ .Values.config.development }}
    slack:
      enabled: {{ .Values.config.slack.enabled }}
      url: {{ .Values.config.slack.url }}
    earlyexpire:
      anchor: {{ .Values.config.earlyexpire.anchor }}
      issuer: {{ .Values.config.earlyexpire.issuer }}
kind: ConfigMap
metadata:
  name: {{ include "linkerd-cert-notifier.fullname" . }}