apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "linkerd-cert-notifier.fullname" . }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      backoffLimit: 6
      completions: 1
      parallelism: 1
      selector:
        matchLabels:
          {{- include "linkerd-cert-notifier.selectorLabels" . | nindent 10 }}
      template:
        metadata:
          labels:
            {{- include "linkerd-cert-notifier.selectorLabels" . | nindent 12 }}
        spec:
          containers:
          - image: {{ .Values.image }}:{{ .Values.tag | default "latest" }}
            imagePullPolicy: IfNotPresent
            name: linkerd-cert-notifier
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /config
              name: config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          terminationGracePeriodSeconds: 30
          serviceAccountName: {{ include "linkerd-cert-notifier.serviceAccountName" . }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: config
            configMap:
              defaultMode: 420
              name: {{ include "linkerd-cert-notifier.fullname" . }}