name: Run tests and build in branch
on:
  push:
    branches: 
      - '*'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build latest
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint ./...

    - name: Test
      run: go test -v ./...


    - name: Build
      run: go build -v .

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
    - name: Upload result to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif