name: Run tests and build in branch
on:
  push:
    branches: 
      - '*'
      - '!master'

jobs:
  test:
    name: Build latest
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint ./...

    - name: Test
      run: go test -v ./...


    - name: Build
      run: go build -v .