name: Build latest from main branch
on:
  push:
    branches: 
      - main

jobs:
  test:
    name: Build latest
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint ./...
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
    - name: Upload result to Github Code Scanning
      uses: github/codeql-action/upload-sarif-file@v1
      with:
        sarif_file: snyk.sarif

    - name: Install KO
      run: |
        curl -L https://github.com/google/ko/releases/download/v0.8.3/ko_0.8.3_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko

    - name: Publish docker image
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
      run: |
        ./ko login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        ./ko publish -B .