name: Build release from tag
on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
    - name: Get version from tags
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint ./...
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

    - name: Install KO
      run: |
        curl -L https://github.com/google/ko/releases/download/v0.8.3/ko_0.8.3_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko

    - name: Publish docker image
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
      run: |
        ./ko login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
        ./ko publish -B --tags v${{ steps.version.outputs.tag }} .
  release:
    name: Releasenotes
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.1.0
        with:
          configuration: ".release-configs/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}